User.create(full_name: "Test Testov", email: "test@test.test", password: "Testtest", password_confirmation: "Testtest")
Post.create(user_id: 1, title: "Dirty Dozen", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.")
Comment.create(user_id: 1, post_id: 1, content: "Nice post, I love it!")
User.create(full_name: "Test Testov 2", email: "test2@test.test", password: "Testtest", password_confirmation: "Testtest")
Comment.create(user_id: 2, post_id: 1, content: "I agree with Test Testov. It's a really good post. Any subscribe button?")
